# Pandas DataFrames - Lab Practice Sheet

In [3]:
import numpy as np
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 120)

## Section A - Easy
### 1. Create `student_df`

In [4]:
student_data = {
    'Name': ['Aarav', 'Diya', 'Kabir', 'Anaya'],
    'Age': [19, 20, 18, 21],
    'City': ['Delhi', 'Mumbai', 'Pune', 'Lucknow'],
}
student_df = pd.DataFrame(student_data, index=['S1', 'S2', 'S3', 'S4'])
student_df

     Name  Age     City
S1  Aarav   19    Delhi
S2   Diya   20   Mumbai
S3  Kabir   18     Pune
S4  Anaya   21  Lucknow

### 2. Display the complete `student_df`

In [5]:
student_df

     Name  Age     City
S1  Aarav   19    Delhi
S2   Diya   20   Mumbai
S3  Kabir   18     Pune
S4  Anaya   21  Lucknow

### 3. Display column names

In [6]:
student_df.columns

Index(['Name', 'Age', 'City'], dtype='str')

### 4. Retrieve the `Name` column

In [7]:
student_df['Name']

S1    Aarav
S2     Diya
S3    Kabir
S4    Anaya
Name: Name, dtype: str

### 5. Retrieve the `City` column using square brackets

In [8]:
student_df['City']

S1      Delhi
S2     Mumbai
S3       Pune
S4    Lucknow
Name: City, dtype: str

### 6. Create a DataFrame containing only `Name` and `City`

In [9]:
student_name_city_df = student_df[['Name', 'City']]
student_name_city_df

     Name     City
S1  Aarav    Delhi
S2   Diya   Mumbai
S3  Kabir     Pune
S4  Anaya  Lucknow

### 7. Create `book_df`

In [10]:
book_data = {
    'Book': ['Python Basics', 'Data Science', 'Machine Learning'],
    'Author': ['A. Sharma', 'R. Mehta', 'S. Verma'],
    'Price': [450, 600, 750]
}
book_df = pd.DataFrame(book_data)
book_df

               Book     Author  Price
0     Python Basics  A. Sharma    450
1      Data Science   R. Mehta    600
2  Machine Learning   S. Verma    750

### 8. Add the `Publisher` column

In [11]:
book_df['Publisher'] = 'Tech Publications'
book_df

               Book     Author  Price          Publisher
0     Python Basics  A. Sharma    450  Tech Publications
1      Data Science   R. Mehta    600  Tech Publications
2  Machine Learning   S. Verma    750  Tech Publications

### 9. Assign `np.arange(5)` to `SerialNo`

In [12]:
serial_df = pd.DataFrame({
    'Item': ['A', 'B', 'C', 'D', 'E']
})
serial_df['SerialNo'] = np.arange(5)
serial_df

  Item  SerialNo
0    A         0
1    B         1
2    C         2
3    D         3
4    E         4

### 10. Delete the `SerialNo` column

In [13]:
serial_df = serial_df.drop(columns='SerialNo')
serial_df

  Item
0    A
1    B
2    C
3    D
4    E

### 11. Create `movie_df`

In [14]:
movie_df = pd.DataFrame({
    'Movie': ['Inception', 'Interstellar', 'Dangal'],
    'Year': [2010, 2014, 2016],
    'Rating': [8.8, 8.7, 8.3]
})
movie_df

          Movie  Year  Rating
0     Inception  2010     8.8
1  Interstellar  2014     8.7
2        Dangal  2016     8.3

### 12. Select columns and add a missing `Director` column

In [15]:
movie_selected_df = movie_df.reindex(columns=['Movie', 'Rating', 'Director'])
movie_selected_df

          Movie  Rating  Director
0     Inception     8.8       NaN
1  Interstellar     8.7       NaN
2        Dangal     8.3       NaN

### 13. Create a Series with indexes 0 and 3

In [16]:
city_series = pd.Series(['Delhi', 'Pune'], index=[0, 3])
city_series

0    Delhi
3     Pune
dtype: str

### 14. Assign the Series to `Branch`

In [17]:
branch_df = pd.DataFrame({'Student': ['A', 'B', 'C', 'D']})
branch_df['Branch'] = city_series
branch_df

  Student Branch
0       A  Delhi
1       B    NaN
2       C    NaN
3       D   Pune

### 15. Read a copied table with `pd.read_clipboard()`

In [18]:
# Copy a tabular dataset first, then run this cell.
# On some systems, use pd.read_clipboard(sep='\t').
copied_df = pd.read_clipboard()
copied_df

Empty DataFrame
Columns: [C:\Users\Lavnish, singh\.gemini\antigravity\scratch\monte_carlo_finance\]
Index: []

## Section B - Moderate
### 16. Create `employee_df` and select two columns

In [19]:
employee_df = pd.DataFrame({
    'Employee': ['E001', 'E002', 'E003', 'E004', 'E005'],
    'Department': ['IT', 'HR', 'Finance', 'Marketing', 'IT'],
    'Experience': [2, 4, 1, 5, 3]
})
employee_experience_df = employee_df[['Employee', 'Experience']]
employee_experience_df

  Employee  Experience
0     E001           2
1     E002           4
2     E003           1
3     E004           5
4     E005           3

### 17. Retrieve `Department` and display all column names

In [20]:
employee_df['Department']
employee_df.columns

Index(['Employee', 'Department', 'Experience'], dtype='str')

### 18. Add `Office` with the same value

In [21]:
employee_df['Office'] = 'Head Office'
employee_df

  Employee Department  Experience       Office
0     E001         IT           2  Head Office
1     E002         HR           4  Head Office
2     E003    Finance           1  Head Office
3     E004  Marketing           5  Head Office
4     E005         IT           3  Head Office

### 19. Replace `Office` using `np.arange(5)`

In [22]:
employee_df['Office'] = np.arange(5)
employee_df

  Employee Department  Experience  Office
0     E001         IT           2       0
1     E002         HR           4       1
2     E003    Finance           1       2
3     E004  Marketing           5       3
4     E005         IT           3       4

### 20. Assign a partially indexed `office_names` Series

In [23]:
office_names = pd.Series(['Delhi', 'Mumbai', 'Pune'], index=[0, 2, 4], name='Office')
employee_df['Office'] = office_names
employee_df

  Employee Department  Experience  Office
0     E001         IT           2   Delhi
1     E002         HR           4     NaN
2     E003    Finance           1  Mumbai
3     E004  Marketing           5     NaN
4     E005         IT           3    Pune

### 21. Delete the `Office` column

In [24]:
employee_df = employee_df.drop(columns='Office')
employee_df

  Employee Department  Experience
0     E001         IT           2
1     E002         HR           4
2     E003    Finance           1
3     E004  Marketing           5
4     E005         IT           3

### 22. Create `product_df` and reorder columns

In [25]:
product_df = pd.DataFrame({
    'Product': ['Laptop', 'Mouse', 'Keyboard'],
    'Category': ['Electronics', 'Accessories', 'Accessories'],
    'Price': [65000, 800, 1500]
})
product_reordered_df = product_df[['Price', 'Product', 'Category']]
product_reordered_df

   Price   Product     Category
0  65000    Laptop  Electronics
1    800     Mouse  Accessories
2   1500  Keyboard  Accessories

### 23. Request a non-existent column

In [26]:
source_df = pd.DataFrame({
    'Name': ['A', 'B', 'C'],
    'Score': [85, 90, 78]
})
requested_df = source_df.reindex(columns=['Name', 'Score', 'Grade'])
requested_df

# The missing Grade column contains NaN values.

  Name  Score  Grade
0    A     85    NaN
1    B     90    NaN
2    C     78    NaN

### 24. Retrieve a column containing a space

In [27]:
marks_df = pd.DataFrame({
    'Student': ['A', 'B', 'C'],
    'Total Marks': [88, 76, 94]
})
marks_df['Total Marks']

0    88
1    76
2    94
Name: Total Marks, dtype: int64

### 25. Read a copied table and select three columns

In [28]:
# Copy a table before running this cell.
copied_table_df = pd.read_clipboard()
print(copied_table_df.columns)
selected_three_df = copied_table_df.iloc[:, :3]
selected_three_df

Index(['C:\Users\Lavnish', 'singh\.gemini\antigravity\scratch\monte_carlo_finance\'], dtype='str')

Empty DataFrame
Columns: [C:\Users\Lavnish, singh\.gemini\antigravity\scratch\monte_carlo_finance\]
Index: []

## Section C - Hard
### 26. Create `course_df` and perform the requested operations

In [29]:
course_df = pd.DataFrame({
    'Student': ['Aarav', 'Diya', 'Kabir', 'Anaya', 'Rohan'],
    'Course': ['Python', 'Statistics', 'Pandas', 'NumPy', 'SQL'],
    'Score': [85, 91, 88, 79, 94]
})

course_df.columns
course_df['Student']
course_student_score_df = course_df[['Student', 'Score']]
course_df['Batch'] = '2026'
course_df

  Student      Course  Score Batch
0   Aarav      Python     85  2026
1    Diya  Statistics     91  2026
2   Kabir      Pandas     88  2026
3   Anaya       NumPy     79  2026
4   Rohan         SQL     94  2026

### 27. Add and replace `Code` in `travel_df`

In [30]:
travel_df = pd.DataFrame({
    'Traveler': ['A', 'B', 'C', 'D', 'E'],
    'Destination': ['Delhi', 'Goa', 'Jaipur', 'Kochi', 'Manali'],
    'Days': [2, 4, 3, 5, 6]
})

travel_df['Code'] = np.arange(5)
print('After assigning np.arange(5):')
print(travel_df)

travel_codes = pd.Series(['TR-101', 'TR-104'], index=[1, 4], name='Code')
travel_df['Code'] = travel_codes
print('After assigning the partially indexed Series:')
print(travel_df)

After assigning np.arange(5):
  Traveler Destination  Days  Code
0        A       Delhi     2     0
1        B         Goa     4     1
2        C      Jaipur     3     2
3        D       Kochi     5     3
4        E      Manali     6     4
After assigning the partially indexed Series:
  Traveler Destination  Days    Code
0        A       Delhi     2     NaN
1        B         Goa     4  TR-101
2        C      Jaipur     3     NaN
3        D       Kochi     5     NaN
4        E      Manali     6  TR-104

### 28. Add and fill the missing `House` column

In [31]:
school_df = pd.DataFrame({
    'Student': ['A', 'B', 'C', 'D'],
    'Class': [10, 10, 11, 11],
    'Section': ['A', 'B', 'A', 'B']
})

school_extended_df = school_df.reindex(columns=['Student', 'Class', 'Section', 'House'])
school_extended_df['House'] = 'Tagore House'
school_extended_df

  Student  Class Section         House
0       A     10       A  Tagore House
1       B     10       B  Tagore House
2       C     11       A  Tagore House
3       D     11       B  Tagore House

### 29. Add a partially indexed Series and delete it

In [32]:
inventory_df = pd.DataFrame({
    'Item': ['Pen', 'Notebook', 'Pencil', 'Eraser'],
    'Quantity': [20, 15, 30, 10],
    'Price': [10, 50, 5, 8]
})

stock_locations = pd.Series(['Shelf A', 'Shelf C'], index=[0, 2], name='Location')
inventory_df['Location'] = stock_locations
print('After adding Location:')
print(inventory_df)

inventory_df = inventory_df.drop(columns='Location')
print('After deleting Location:')
print(inventory_df)

After adding Location:
       Item  Quantity  Price Location
0       Pen        20     10  Shelf A
1  Notebook        15     50      NaN
2    Pencil        30      5  Shelf C
3    Eraser        10      8      NaN
After deleting Location:
       Item  Quantity  Price
0       Pen        20     10
1  Notebook        15     50
2    Pencil        30      5
3    Eraser        10      8

### 30. Complete sequence using `lab_df`

In [33]:
# Copy a table with at least four columns before running this cell.
lab_df = pd.read_clipboard()

print('Complete DataFrame:')
print(lab_df)

print('Column names:')
print(lab_df.columns)

# Retrieve the first single-word column.
single_word_columns = [col for col in lab_df.columns if ' ' not in str(col)]
if single_word_columns:
    print('Single-word column:')
    print(lab_df[single_word_columns[0]])

# Retrieve the first column whose name contains a space.
space_columns = [col for col in lab_df.columns if ' ' in str(col)]
if space_columns:
    print('Column containing a space:')
    print(lab_df[space_columns[0]])

# Construct a smaller DataFrame from the first three available columns.
selected_columns = list(lab_df.columns[:3])
small_lab_df = lab_df[selected_columns]
print('Smaller DataFrame:')
print(small_lab_df)

# Add and then delete a whole column.
lab_df['PracticeColumn'] = 'Added'
print('After adding PracticeColumn:')
print(lab_df)

lab_df = lab_df.drop(columns='PracticeColumn')
print('After deleting PracticeColumn:')
print(lab_df)

Complete DataFrame:
Empty DataFrame
Columns: [C:\Users\Lavnish, singh\.gemini\antigravity\scratch\monte_carlo_finance\]
Index: []
Column names:
Index(['C:\Users\Lavnish', 'singh\.gemini\antigravity\scratch\monte_carlo_finance\'], dtype='str')
Single-word column:
Series([], Name: C:\Users\Lavnish, dtype: object)
Smaller DataFrame:
Empty DataFrame
Columns: [C:\Users\Lavnish, singh\.gemini\antigravity\scratch\monte_carlo_finance\]
Index: []
After adding PracticeColumn:
Empty DataFrame
Columns: [C:\Users\Lavnish, singh\.gemini\antigravity\scratch\monte_carlo_finance\, PracticeColumn]
Index: []
After deleting PracticeColumn:
Empty DataFrame
Columns: [C:\Users\Lavnish, singh\.gemini\antigravity\scratch\monte_carlo_finance\]
Index: []